####################################################################
#                                                                  #
# Override Pi-KVM system settings. This file uses the YAML syntax. #
#                                                                  #
#    https://github.com/pikvm/pikvm/blob/master/pages/config.md    #
#                                                                  #
# All overridden parameters will be applied AFTER other configs    #
# and "!include" directives and BEFORE validation.                 #
# Not: Sections should be combined under shared keys.              #
#                                                                  #
####################################################################
vnc:
    # See https://github.com/pikvm/pikvm/blob/master/pages/vnc.md
    keymap: /usr/share/kvmd/keymaps/ru # Set russian keymap
    auth:
        vncauth:
            enabled: true # Enable auth via /etc/kvmd/vncpasswd
kvmd:
    msd:
        type: disabled
    gpio:
        drivers:
            wol_server1:
                type: wol
                mac: 2c:56:dc:db:7c:1e
            short_press:
                type: cmd
                cmd: [/usr/bin/sudo, short_press_gpio420]
            long_press:
                type: cmd
                cmd: [/usr/bin/sudo, long_press_gpio420]
        scheme:
            wol_server1:
                driver: wol_server1
                pin: 0
                mode: output
                switch: false
            short_button:
                driver: short_press
                pin: 0
                mode: output
                switch: false
            long_button:
                driver: long_press
                pin: 0
                mode: output
                switch: false
        view:
            header:
                title: ATX
            table:
                - ["#电源管理"]
                - []
                - ["#短按（开/关机）:", short_button|按下]
                - ["#长按（强制关机）:", long_button|按下]
                - []
                - ["#网络唤醒"]
                - ["#被控机设备", wol_server1|网络唤醒]
